version: 0.0
os: linux
files:
  - source: /target/  # Wskazanie na artefakt
    destination: /home/ubuntu/myapp/target/  # Docelowy folder na EC2
    overwrite: yes
  - source: /scripts/  # Wskazanie na artefakt
    destination: /home/ubuntu/myapp/scripts/  # Docelowy folder na EC2
    overwrite: yes
  - source: /Dockerfile  # Wskazanie na artefakt
    destination: /home/ubuntu/myapp/Dockerfile  # Docelowy folder na EC2
    overwrite: yes
hooks:
  AfterInstall:
    - location: scripts/deploy_application.sh
      timeout: 300
      runas: root
