version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn install
  build:
    commands:
      - echo Building the application...
      - mvn package
  post_build:
    commands:
      - echo "Jestem w katalogu:"
      - pwd
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml



