version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - java -version
      - mvn install
  build:
    commands:
      - echo Building the application...
      - java -version
      - mvn package
  post_build:
    commands:
      - echo "Jestem w katalogu:"
      - pwd
      - ls
      - chmod +x scripts/deploy_application.sh
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
    - Dockerfile



