version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn install
  build:
    commands:
      - echo Building the application...
      - mvn package

artifacts:
  files:
    - target/*.jar
