version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn install
  build:
    commands:
      - echo Building the application...
      - mvn package

artifacts:
  files:
    - target/*.jar
  name: myapp-$(date +%Y%m%d%H%M%S).zip
  discard-paths: yes
  secondary-artifacts:
    - name: manifest.json
      files:
        - manifest.json
      base-directory: target/
