version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn install
  build:
    commands:
      - echo Building the application...
      - mvn package
  post_build:
    commands:
      - chmod +x scripts/deploy_docker_container.sh
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
    - Dockerfile



